# Clase 13 Creando un Dataframe

### Importamos nuestra librería de pandas

In [1]:
import pandas as pd

### Creamos un Dataframe vacío

In [2]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [3]:
print(df)

Empty DataFrame
Columns: []
Index: []

### Creamos un Dataframe con diccionarios

In [4]:
empresas= {'Empresas':['Empresa A','Empresa B','Empresa C','Empresa D'],
            'Ventas':[1500000,2000000,1234000,100000],
            'Costos':[600000,543678,235453,21464],
            'Ciudad':['Buenos Aires','Los Angeles','México','Miami'],
            'Piezas':[500,1234,6542,2344]}

In [5]:
df=pd.DataFrame(empresas)
df

    Empresas   Ventas  Costos        Ciudad  Piezas
0  Empresa A  1500000  600000  Buenos Aires     500
1  Empresa B  2000000  543678   Los Angeles    1234
2  Empresa C  1234000  235453        México    6542
3  Empresa D   100000   21464         Miami    2344

### Creamos un Dataframe con listas

In [8]:
jugadores=[['Lebron','Hoford'],[30,25]]

In [12]:
# Indices y columnas
df=pd.DataFrame(jugadores,columns=['Jugadores','Puntos'],index=['Jugadores','Puntos'])
df

          Jugadores  Puntos
Jugadores    Lebron  Hoford
Puntos           30      25

### Creamos un Dataframe con excel

In [13]:
#primero indicamos la ruta del excel, usar back slashes
path='C:\\Users\\Gabo\\Documents\\Gabriel Mendoza\\Business\\Crehana\\El ABC de Jupyter Notebook y Anaconda\\Material\\04 Módulo 4\\Clase 13\\NBA Data Base.xlsx'

In [14]:
df=pd.read_excel(path)
df

,TEAM_ABBREVIATION,TEAM_NAME,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PLUS_MINUS,Game Type,Season,GAME_NUM,Round
0,DAL,Dallas Mavericks,2011-06-12,DAL @ MIA,W,240,105,41,82,0.500,...,19,11,1,14,24,10.0,Playoff,2010-11,6,NBA Finals
1,DAL,Dallas Mavericks,2011-06-09,DAL vs. MIA,W,241,112,39,69,0.565,...,23,8,3,11,20,9.0,Playoff,2010-11,5,NBA Finals
2,DAL,Dallas Mavericks,2011-06-07,DAL vs. MIA,W,240,86,29,73,0.397,...,13,7,2,11,18,3.0,Playoff,2010-11,4,NBA Finals
3,MIA,Miami Heat,2011-06-05,MIA @ DAL,W,239,88,34,78,0.436,...,20,8,5,10,27,2.0,Playoff,2010-11,3,NBA Finals
4,DAL,Dallas Mavericks,2011-06-02,DAL @ MIA,W,240,95,36,75,0.480,...,18,8,2,18,20,2.0,Playoff,2010-11,2,NBA Finals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15771,LAL,Los Angeles Lakers,2021-08-04,LAL @ SAC,W,240,84,27,67,0.403,...,11,11,5,14,13,4.0,Regular,22021,Regular,Regular
15772,MIA,Miami Heat,2021-08-04,MIA @ GSW,W,240,94,31,65,0.477,...,19,13,4,21,17,13.2,Regular,22021,Regular,Regular
15773,GSW,Golden State Warriors,2021-08-03,GSW @ SAC,W,265,89,33,76,0.434,...,18,4,6,16,20,1.0,Regular,22021,Regular,Regular
15774,MIA,Miami Heat,2021-08-03,MIA vs. LAL,W,241,80,33,71,0.465,...,18,10,4,19,21,2.0,Regular,22021,Regular,Regular
15775,MEM,Memphis Grizzlies,2021-08-03,MEM @ UTB,W,200,104,41,86,0.477,...,26,10,12,12,15,39.0,Regular,22021,Regular,Regular

### Creamos un Dataframe con csv

In [15]:
path='C:\\Users\\Gabo\\Documents\\Gabriel Mendoza\\Business\\Crehana\\El ABC de Jupyter Notebook y Anaconda\\Material\\04 Módulo 4\\Clase 13\\NBA Data Base.csv'

In [16]:
df=pd.read_csv(path)
df

,TEAM_ABBREVIATION,TEAM_NAME,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PLUS_MINUS,Game Type,Season,GAME_NUM,Round
0,DAL,Dallas Mavericks,12/6/2011,DAL @ MIA,W,240,105,41,82,0.500,...,19,11,1,14,24,10.0,Playoff,2010-11,6,NBA Finals
1,DAL,Dallas Mavericks,9/6/2011,DAL vs. MIA,W,241,112,39,69,0.565,...,23,8,3,11,20,9.0,Playoff,2010-11,5,NBA Finals
2,DAL,Dallas Mavericks,7/6/2011,DAL vs. MIA,W,240,86,29,73,0.397,...,13,7,2,11,18,3.0,Playoff,2010-11,4,NBA Finals
3,MIA,Miami Heat,5/6/2011,MIA @ DAL,W,239,88,34,78,0.436,...,20,8,5,10,27,2.0,Playoff,2010-11,3,NBA Finals
4,DAL,Dallas Mavericks,2/6/2011,DAL @ MIA,W,240,95,36,75,0.480,...,18,8,2,18,20,2.0,Playoff,2010-11,2,NBA Finals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15771,LAL,Los Angeles Lakers,4/8/2021,LAL @ SAC,W,240,84,27,67,0.403,...,11,11,5,14,13,4.0,Regular,22021,Regular,Regular
15772,MIA,Miami Heat,4/8/2021,MIA @ GSW,W,240,94,31,65,0.477,...,19,13,4,21,17,13.2,Regular,22021,Regular,Regular
15773,GSW,Golden State Warriors,3/8/2021,GSW @ SAC,W,265,89,33,76,0.434,...,18,4,6,16,20,1.0,Regular,22021,Regular,Regular
15774,MIA,Miami Heat,3/8/2021,MIA vs. LAL,W,241,80,33,71,0.465,...,18,10,4,19,21,2.0,Regular,22021,Regular,Regular
15775,MEM,Memphis Grizzlies,3/8/2021,MEM @ UTB,W,200,104,41,86,0.477,...,26,10,12,12,15,39.0,Regular,22021,Regular,Regular